name : Continuous Integration

on: 
  pull_request: 
    branches:
      -main

jobs: 
  test: 
  runs-on: ubuntu-latest

  strategy: 
    matrix:
      node-version: [14.x]
  
  steps: 
    - uses: action/checkout@v3
    - name: Use node.js ${{ matrix.node-version }}
      uses: action/setup-node@v3
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Run Automated Tested
      run: 
      npm i
      npm run test
